import type { ThemeConfig } from "antd";

export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: "#3B82F6",
    colorPrimaryHover: "#2563EB",
    colorPrimaryActive: "#1D4ED8",
    colorSuccess: "#16A34A",
    colorWarning: "#F59E0B",
    colorError: "#EF4444",
    colorInfo: "#3B82F6",
    colorText: "#111827",
    colorTextSecondary: "#4B5563",
    colorTextTertiary: "#6B7280",
    colorTextQuaternary: "#9CA3AF",
    colorTextPlaceholder: "#9CA3AF",
    colorBgBase: "#F7F8FA",
    colorBgLayout: "#F3F4F6",
    colorBgContainer: "#FFFFFF",
    colorBgElevated: "#FFFFFF",
    colorBorder: "#E5E7EB",
    colorBorderSecondary: "#EDF0F3",
    colorSplit: "#EEF2F7",
    colorFill: "#F1F5F9",
    colorFillSecondary: "#E9EEF5",
    colorFillTertiary: "#F5F7FA",
    colorFillQuaternary: "#F9FAFB",
    colorLink: "#3B82F6",
    colorLinkHover: "#2563EB",
    colorLinkActive: "#1D4ED8",
    fontFamily:
      "\"Source Sans 3\", \"Segoe UI Variable\", \"Segoe UI\", \"SF Pro Text\", \"Helvetica Neue\", \"Noto Sans\", sans-serif",
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    lineHeight: 1.5,
    lineHeightSM: 1.4,
    lineHeightLG: 1.6,
    borderRadius: 8,
    borderRadiusSM: 6,
    borderRadiusLG: 12,
    controlHeight: 32,
    controlHeightSM: 28,
    controlHeightLG: 36,
    sizeUnit: 4,
    sizeStep: 4,
    sizeXS: 8,
    sizeSM: 12,
    size: 16,
    sizeLG: 24,
    sizeXL: 32,
    motionDurationFast: "100ms",
    motionDurationMid: "200ms",
    motionDurationSlow: "300ms",
  },
  components: {
    Button: {
      fontWeight: 500,
      defaultShadow: "none",
      primaryShadow: "none",
      dangerShadow: "none",
      defaultBg: "#FFFFFF",
      defaultBorderColor: "#D0D7E2",
      paddingInline: 12,
      paddingInlineSM: 10,
      paddingInlineLG: 16,
      paddingBlock: 6,
      paddingBlockSM: 4,
      paddingBlockLG: 8,
    },
    Input: {
      paddingInline: 10,
      paddingInlineSM: 8,
      paddingInlineLG: 12,
      paddingBlock: 6,
      paddingBlockSM: 4,
      paddingBlockLG: 8,
      hoverBorderColor: "#93C5FD",
      activeBorderColor: "#3B82F6",
    },
    Card: {
      headerBg: "#FFFFFF",
      bodyPadding: 16,
      bodyPaddingSM: 12,
      headerPadding: 16,
      headerPaddingSM: 12,
    },
    Layout: {
      headerBg: "#FFFFFF",
      siderBg: "#F8FAFC",
      bodyBg: "#F7F8FA",
    },
    Menu: {
      itemHeight: 36,
      itemPaddingInline: 12,
      itemHoverBg: "#F1F5F9",
      itemSelectedBg: "#E8F0FF",
      itemSelectedColor: "#1D4ED8",
    },
    List: {
      itemPadding: "12px 16px",
      itemPaddingSM: "8px 12px",
      itemPaddingLG: "16px 20px",
    },
    Table: {
      headerBg: "#F9FAFB",
      rowHoverBg: "#F5F7FA",
      borderColor: "#EEF2F7",
      cellPaddingBlock: 10,
      cellPaddingInline: 12,
      cellPaddingBlockSM: 8,
      cellPaddingInlineSM: 10,
    },
    Tabs: {
      inkBarColor: "#3B82F6",
      itemActiveColor: "#1D4ED8",
      itemHoverColor: "#2563EB",
      itemSelectedColor: "#1D4ED8",
      titleFontSize: 14,
      horizontalItemPadding: "6px 12px",
    },
    Modal: {
      headerBg: "#FFFFFF",
      contentBg: "#FFFFFF",
      footerBg: "#FFFFFF",
      titleFontSize: 16,
      titleLineHeight: 1.4,
      titleColor: "#111827",
    },
  },
};
